DROP TABLE IF EXISTS `#__bigtownwalk_walks`;

CREATE TABLE `#__bigtownwalk_walks` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL DEFAULT '',
	`alias` VARCHAR(100) NOT NULL DEFAULT '',
	`created` DATETIME NULL DEFAULT NULL,
	`created_by` INT(10) NOT NULL DEFAULT '0',
	`description` TEXT NOT NULL,
	`modified` DATETIME NULL DEFAULT NULL,
	`attribs` TEXT NOT NULL,
	`state` TINYINT(3) NOT NULL DEFAULT '0',
	`publish_up` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`publish_down` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`access` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb4;
